"use client";

import React, { useState } from "react";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from 'next/head'
import "./globals.css";
import ShowMenu from "@/components/ShowMenu";
import { Toaster } from "react-hot-toast";
import Settings from "../components/Settings";
import { ResavationAppProvider } from '../context/ResavationContextApp'

// import { ResavationAppProvider } from '../context/ResavationContextApp'
// export const metadata = {
//   title: 'Resavation Website',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [showMenu, setShowMenu] = useState(false);
  const [showSettings, setShowSettings] = useState(false);

  return (
    <html lang="en">
      <Head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
        <link rel="icon" href="/favicon1.ico" sizes="any" />
      </Head>
      {!showMenu && !showSettings && (<>
        <body className="chatScroll relative bg-[#ffffff] w-full h-screen px-1">
          <ResavationAppProvider>
              <Navbar setShowMenu={setShowMenu} setShowSettings={setShowSettings} />
              {children}
              <Footer />
          </ResavationAppProvider>
          
          <Toaster />
         <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
        </body>
        </>)}
      {showMenu && (
        <body className="relative bg-[#f5f5f5] w-full md:px-32 py-2">
          <ResavationAppProvider>
            <ShowMenu setShowMenu={setShowMenu} />
          </ResavationAppProvider>
        </body>
      )}

      {showSettings && (
        <body className="relative bg-[#f5f5f5] w-full md:px-32 py-2 md:hidden">
          <ResavationAppProvider>
            <Settings setShowSettings={setShowSettings} />
          </ResavationAppProvider>
         
        </body>
      )}
    </html>
  );
}
